### ISSUE TITLE
'cargo install pwatch' fails with errors

### ISSUE THREAD

**Issue by olivier-fs** [VladimirMarkelov/pwatch#11]
Hi!
Just wanted to try pwatch but install fails on my box (rust-1.63.0 (stable), Windows 10)

$ cargo install pwatch
    Updating crates.io index
  Downloaded pwatch v0.4.0
  Downloaded 1 crate (154.1 KB) in 2.26s
  Installing pwatch v0.4.0
  Downloaded sysinfo v0.26.1
  Downloaded 1 crate (128.8 KB) in 1.51s
   Compiling autocfg v1.1.0
...
... 
...
   Compiling pwatch v0.4.0                                                                                                             
error[E0432]: unresolved import `sysinfo::ProcessorExt`                                                                                
  --> C:\Users\olivier\.cargo\registry\src\github.com-1ecc6299db9ec823\pwatch-0.4.0\src\layout.rs:10:27                                
   |                                                                                                                                   
10 | use sysinfo::{ProcessExt, ProcessorExt, System, SystemExt};                                                                       
   |                           ^^^^^^^^^^^^                                                                                            
   |                           |                                                                                                       
   |                           no `ProcessorExt` in the root                                                                           
   |                           help: a similar name exists in the module: `ProcessExt`                                                 
                                                                                                                                       
error[E0605]: non-primitive cast: `usize` as `Pid`                                                                                     
   --> C:\Users\olivier\.cargo\registry\src\github.com-1ecc6299db9ec823\pwatch-0.4.0\src\config.rs:286:36                              
    |                                                                                                                                  
286 |                 conf.pid_list.push(i as Pid);                                                                                    
    |                                    ^^^^^^^^ help: consider using the `From` trait instead: `Pid::from(i)`                        
    |                                                                                                                                  
    = note: an `as` expression can only be used to convert between primitive types or to coerce to a specific trait object             
                                                                                                                                       
error[E0599]: no method named `get_processes` found for struct `sysinfo::System` in the current scope                                  
  --> C:\Users\olivier\.cargo\registry\src\github.com-1ecc6299db9ec823\pwatch-0.4.0\src\layout.rs:64:33                                
   |                                                                                                                                   
64 |         let procs = self.system.get_processes();                                                                                  
   |                                 ^^^^^^^^^^^^^ method not found in `sysinfo::System`                                               
                                                                                                                                       
error[E0599]: no method named `get_processors` found for struct `sysinfo::System` in the current scope                                 
   --> C:\Users\olivier\.cargo\registry\src\github.com-1ecc6299db9ec823\pwatch-0.4.0\src\layout.rs:119:31                              
    |                                                                                                                                  
119 |         for pr in self.system.get_processors().iter() {                                                                          
    |                               ^^^^^^^^^^^^^^ method not found in `sysinfo::System`                                               
                                                                                                                                       
error[E0599]: no method named `get_used_memory` found for struct `sysinfo::System` in the current scope                                
   --> C:\Users\olivier\.cargo\registry\src\github.com-1ecc6299db9ec823\pwatch-0.4.0\src\layout.rs:125:38                              
    |                                                                                                                                  
125 |         self.mem_usage = self.system.get_used_memory() * 100 / self.system.get_total_memory();                                   
    |                                      ^^^^^^^^^^^^^^^ method not found in `sysinfo::System`                                       
                                                                                                                                       
error[E0599]: no method named `get_total_memory` found for struct `sysinfo::System` in the current scope                               
   --> C:\Users\olivier\.cargo\registry\src\github.com-1ecc6299db9ec823\pwatch-0.4.0\src\layout.rs:125:76                              
    |                                                                                                                                  
125 |         self.mem_usage = self.system.get_used_memory() * 100 / self.system.get_total_memory();                                   
    |                                                                            ^^^^^^^^^^^^^^^^ method not found in `sysinfo::System`

Most of the error messages are explicit.

crate sysinfo has renamed some symbols e.g.

0.24.0 : Rename `Processor` into `Cpu` and `ProcessorExt` into `CpuExt`.
(https://github.com/GuillaumeGomez/sysinfo/search?q=processorext)

but pwatch Cargo.toml only has 

[dependencies]
sysinfo=">=0.14"

Should be easy to fix. Hope this helps

**Comment by VladimirMarkelov** [comment]
Thank you for the report!

Updated all dependencies(to fix vulnerabilities) and made the app to build without errors -> `v.0.5.2`

**Comment by olivier-fs** [comment]
I confirm : v0.5.2 now builds (and runs) fine on my my box.
As you've published the crate you can close this issue at will if nobody else reports any problem.
Great job, quickly done!

**Comment by VladimirMarkelov** [comment]
Thank you!
